apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "statics.fullname" . }}
  labels:
    app: {{ template "statics.name" . }}
    chart: {{ template "statics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.files | indent 2 }}
